# Generated by Django 4.0 on 2022-01-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_remove_poll_voter_poll_voter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='voter',
            new_name='voters',
        ),
    ]
