# Generated by Django 4.0 on 2022-01-02 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0003_rename_voter_poll_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='polls', to=settings.AUTH_USER_MODEL),
        ),
    ]
